### PR TITLE
Update plugin ID to match package name

### LINKED ISSUE #10: Plugin ID does not match npm package name
See here for why it's an issue
https://github.com/xseignard/cordovarduino/issues/59#issuecomment-265990978

### PR DESCRIPTION
**Pull request by asztal**
Resolves #10

### CODE REVIEW

**Comment by worm-emoji** [comment]
Thanks!

**Comment by asztal** [comment]
Thanks a lot for your quick response, much appreciated!
Is there a chance you could publish to npm as well so that `cordova plugin install` works? 

(Maybe as 2.0.0, I'm not sure how it would affect anyone who already has it installed)

Thanks!

**Comment by worm-emoji** [comment]
Did I not do it correctly? I already published a new version immediately after merging your commit.

**Comment by asztal** [comment]
My mistake, I didn't even think to look for some reason... :man_facepalming: 

It works a treat, thanks!

**Pull request merged**
